### PR TITLE
Improve ufbxi_fetch_maps with more PBR textures

### PR DESCRIPTION
**Pull request by kvark**
Hopefully this will end up in strong-types branch as well. Let me know if you want a separate PR.

### CODE REVIEW

**Comment by bqqbarbhg** [comment]
Thanks! Looks like a clear typo to me, I'll merge it through `master` to `strong-types` a bit later (and probably add some testing for it).

**Comment by bqqbarbhg** [comment]
By the way, did this cause an actual issue with some file or was it just code cleanup? Looking at the history it seems like I added these for FBX version 5000 and below, which are extremely rare. Would be good to know for testing if there's something else that depends on these.

**Comment by bqqbarbhg** [comment]
By the way, did this cause an actual issue with some file or was it just code cleanup? Looking at the history it seems like I added these for FBX version 5000 and below, which are extremely rare. Would be good to know for testing if there's something else that depends on these.

**Comment by kvark** [comment]
Not an actual issue I hit. I was just trying to get transparency texture out of uFBX, noticed this on the way.
But in the end, it's the same problem as #41 - the transparency map is hidden indirectly behind a 3DMax property.

**Comment by bqqbarbhg** [comment]
Yeah I'm working on at least handling the first level of properties ([6ecd0a4](https://github.com/bqqbarbhg/ufbx/pull/36/commits/6ecd0a42922c7ed9bfded2c9593c5b71b498b1eb)), need to still think about more complex cases.

**Pull request merged**
